version: '3.9'
services:
  asir_apache:
    image: httpd:latest
    container_name: asir_apache
    ports:
    - '80:80'
    
    networks:
      apache_net:
        ipv4_address: 172.24.0.10
    volumes:
    - ./paginas:/usr/local/apache2/htdocs
    - ./confApache:/usr/local/apache2/conf
    dns:
    - 172.24.0.20
  asir_bind9:
    container_name: asir_bind9
    image: ubuntu/bind9
    platform: linux/amd64
    ports:
      - 53:53
    networks:
      apache_net:
        ipv4_address: 172.24.0.20
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind
  
  asir_cliente:
    container_name: asir_cliente
    image: ubuntu
    networks:
      apache_net:
        ipv4_address: 172.24.0.30
    stdin_open: true # docker run -i
    tty: true # docker run -t
    dns:
      - 172.24.0.20 # el contenedor dns server

  
networks:
  apache_net:
    external: true

   