services: 
  web1:
   image: httpd:2.4
   ports:
     - 80:80
   volumes:
      - ./paginas:/usr/local/apache2/htdocs
      - ./conf:/usr/local/apache2/conf
   container_name: web1
   networks:
    apache_net:
      ipv4_address: 172.28.5.20

  asir_bind9:
    container_name: asir_bind9
    image: ubuntu/bind9
    platform: linux/amd64
    ports:
      - 53:53
    networks:
      apache_net:
        ipv4_address: 172.28.5.1
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind
  
  asir_cliente:
    container_name: asir_cliente
    image: ubuntu
    networks:
      apache_net:
        ipv4_address: 172.28.5.10
    stdin_open: true # docker run -i
    tty: true # docker run -t
    dns:
      - 172.28.5.1 # el contenedor dns server


networks:
  apache_net:
    external: true

   