version: '3.9'
services:
  asir_apache:
    image: httpd:latest
    container_name: asir_apache
    ports:
    - '80:80'
    - '8000:8000'
    networks:
      apache_net:
        ipv4_address: 172.24.0.10
    volumes:
    - ./paginas:/var/www/html
    - ./confApache:/etc/apache2

  asir_bind9:
    container_name: asir_bind9
    image: ubuntu/bind9
    platform: linux/amd64
    ports:
      - 53:53
    networks:
      apache_net:
        ipv4_address: 172.24.0.20
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bin
networks:
  apache_net:
    external: true

   